"""Add organized_tournaments relationship to User model

Revision ID: 0ba71d67783a
Revises: 97e1aec76825
Create Date: 2025-03-06 08:52:19.552438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ba71d67783a'
down_revision = '97e1aec76825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_member', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_admin'), ['is_admin'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_member'), ['is_member'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('current_participants', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('idx_event_date', ['date'], unique=False)
        batch_op.create_index('idx_event_organizer', ['organizer_id'], unique=False)

    op.create_table('forum_themen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=100), nullable=False),
    sa.Column('inhalt', sa.Text(), nullable=False),
    sa.Column('erstellungsdatum', sa.DateTime(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_themen', schema=None) as batch_op:
        batch_op.create_index('idx_forum_thema_erstellungsdatum', ['erstellungsdatum'], unique=False)
        batch_op.create_index('idx_forum_thema_titel', ['titel'], unique=False)

    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('start_score', sa.Integer(), nullable=True),
    sa.Column('player1_score', sa.Integer(), nullable=True),
    sa.Column('player2_score', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('game_type', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index('idx_game_date_winner', ['date', 'winner_id'], unique=False)
        batch_op.create_index('idx_game_players', ['player1_id', 'player2_id'], unique=False)
        batch_op.create_index('idx_game_type', ['game_type'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('training_hours', sa.Float(), nullable=True),
    sa.Column('highest_score', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('checkout_percentage', sa.Float(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('highest_checkout', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index('idx_player_active', ['active'], unique=False)
        batch_op.create_index('idx_player_name', ['name'], unique=False)
        batch_op.create_index('idx_player_stats', ['average_score', 'games_played', 'wins'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index('idx_post_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_post_is_published', ['is_published'], unique=False)
        batch_op.create_index('idx_post_title', ['title'], unique=False)

    op.create_table('event_participants',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'user_id')
    )
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.create_index('idx_event_participants', ['event_id', 'user_id'], unique=False)

    op.create_table('forum_antworten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inhalt', sa.Text(), nullable=False),
    sa.Column('erstellungsdatum', sa.DateTime(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('thema_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thema_id'], ['forum_themen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_antworten', schema=None) as batch_op:
        batch_op.create_index('idx_forum_antwort_erstellungsdatum', ['erstellungsdatum'], unique=False)
        batch_op.create_index('idx_forum_antwort_thema', ['thema_id'], unique=False)

    op.create_table('game_players',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    with op.batch_alter_table('game_players', schema=None) as batch_op:
        batch_op.create_index('idx_game_players_score', ['game_id', 'player_id', 'score'], unique=False)

    op.create_table('throw_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('angle', sa.Float(), nullable=False),
    sa.Column('velocity', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('game_type', sa.String(length=50), nullable=True),
    sa.Column('target_segment', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('throw_data', schema=None) as batch_op:
        batch_op.create_index('idx_throw_data_player_game', ['player_id', 'game_id'], unique=False)
        batch_op.create_index('idx_throw_data_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['player1_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['winner_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['player2_id'], ['id'])

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['captain_id'], ['id'])

    with op.batch_alter_table('tournament_entries', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['player_id'], ['id'])

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['organizer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('tournament_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('throw_data', schema=None) as batch_op:
        batch_op.drop_index('idx_throw_data_timestamp')
        batch_op.drop_index('idx_throw_data_player_game')

    op.drop_table('throw_data')
    with op.batch_alter_table('game_players', schema=None) as batch_op:
        batch_op.drop_index('idx_game_players_score')

    op.drop_table('game_players')
    with op.batch_alter_table('forum_antworten', schema=None) as batch_op:
        batch_op.drop_index('idx_forum_antwort_thema')
        batch_op.drop_index('idx_forum_antwort_erstellungsdatum')

    op.drop_table('forum_antworten')
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_index('idx_event_participants')

    op.drop_table('event_participants')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('idx_post_title')
        batch_op.drop_index('idx_post_is_published')
        batch_op.drop_index('idx_post_created_at')

    op.drop_table('posts')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index('idx_player_stats')
        batch_op.drop_index('idx_player_name')
        batch_op.drop_index('idx_player_active')

    op.drop_table('players')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index('idx_game_type')
        batch_op.drop_index('idx_game_players')
        batch_op.drop_index('idx_game_date_winner')

    op.drop_table('games')
    with op.batch_alter_table('forum_themen', schema=None) as batch_op:
        batch_op.drop_index('idx_forum_thema_titel')
        batch_op.drop_index('idx_forum_thema_erstellungsdatum')

    op.drop_table('forum_themen')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('idx_event_organizer')
        batch_op.drop_index('idx_event_date')

    op.drop_table('events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_last_seen'))
        batch_op.drop_index(batch_op.f('ix_users_is_member'))
        batch_op.drop_index(batch_op.f('ix_users_is_admin'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
