"""Extended Player model

Revision ID: 51a07edf3e36
Revises: ffb5834b348f
Create Date: 2025-02-28 21:20:40.372710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a07edf3e36'
down_revision = 'ffb5834b348f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('highest_checkout', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('highest_checkout')
        batch_op.drop_column('losses')
        batch_op.drop_column('wins')
        batch_op.drop_column('checkout_percentage')

    # ### end Alembic commands ###
