"""Add role field to User model

Revision ID: 958edab68452
Revises: 0ba71d67783a
Create Date: 2025-03-18 21:08:04.572951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958edab68452'
down_revision = '0ba71d67783a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.drop_index('ix_users_is_admin')
        batch_op.drop_index('ix_users_is_member')
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.drop_column('is_admin')
        batch_op.drop_column('is_member')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_member', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.create_index('ix_users_is_member', ['is_member'], unique=False)
        batch_op.create_index('ix_users_is_admin', ['is_admin'], unique=False)
        batch_op.drop_column('role')

    op.drop_table('questions')
    # ### end Alembic commands ###
