"""Forum models hinzugefügt

Revision ID: ffb5834b348f
Revises: 37cdf65ebb9c
Create Date: 2025-02-28 20:27:10.108582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ffb5834b348f'
down_revision = '37cdf65ebb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_antwort',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inhalt', sa.Text(), nullable=False),
    sa.Column('erstellungsdatum', sa.DateTime(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('thema_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['thema_id'], ['forum_thema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('antwort')
    with op.batch_alter_table('forum_thema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('erstellungsdatum', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('autor_id', sa.Integer(), nullable=False))
        batch_op.alter_column('titel',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'user', ['autor_id'], ['id'])
        batch_op.drop_column('autor')
        batch_op.drop_column('datum')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_thema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datum', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('autor', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('titel',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('autor_id')
        batch_op.drop_column('erstellungsdatum')

    op.create_table('antwort',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('inhalt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('autor', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('thema_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['thema_id'], ['forum_thema.id'], name='antwort_thema_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='antwort_pkey')
    )
    op.drop_table('forum_antwort')
    # ### end Alembic commands ###
